name: videojuego
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/player.png
    - assets/images/player1.png
    - assets/images/enemy.png
    - assets/images/enemy1.png
    - assets/images/background.png
    - assets/images/background2.png
    - assets/images/player_attack.png
